### ISSUE TITLE
How are the AC units exposed on Home app?

### ISSUE THREAD

**Issue by galvesribeiro** [nitaybz/homebridge-cool-automation#2]
Hello!

I've seen the README which shows the main configuration file but it doesn't show how the devices are exposed at the Home App. 

For example, in my case I'm planning to have 1x CoolLinkHub with 4x CoolPlugs. Each of those plugs are connected to each internal split cassete unit from Samsung.

The thing is that each of those CoolPlugs are independent rooms with their own temperatures and I would like to know if they will appear on Home App as its own device controllable on its own, so I can have different automations controlling different environments.

Thank you!

I really appreciate any more info regarding how it really works.

Best regards

**Comment by nitaybz** [comment]
You'll have one accessory (heatercooler) with its own controls, to each of the units/rooms you have...

**Comment by galvesribeiro** [comment]
Sorry but I’ve never seeing a device like that on the Home App. Do you have screenshots with examples?

Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jhulbertpmn** [comment]
> 

Hi - 
These particular screenshots are not backed by this plugin, but the plugin in use is presenting the device to HomeKit as a heatercooler device so will appear very much the same
![Untitled_and_Shop](https://user-images.githubusercontent.com/17837172/146994989-68f94399-5d56-414a-8a56-92ba7145cc2a.png)
![Shop](https://user-images.githubusercontent.com/17837172/146995005-5680ada5-dd1c-4fcf-a667-75c55ae40af9.png)
.

**Comment by SeanHama** [comment]
Can you please confirm if there is a setting which can display the Name instead of UID property in Homebridge/homekit?

**Comment by nitaybz** [comment]
> Can you please confirm if there is a setting which can display the Name instead of UID property in Homebridge/homekit?

you can change the name in the home app, there is no way for me to know the real name
