### ISSUE TITLE
Love this plugin, A change to the useability for HomeKit

### ISSUE THREAD

**Issue by SeanHama** [nitaybz/homebridge-cool-automation#3]
Very nice plugin. Some improvements are needed to ensure the user experience is good for the entire family to save the aircon unit from fault.

1: On the Homekit dashboard, if you click on the Coolplug air con which is set up the aircon unit immediately turns on or off. I would expect that the air-con device "settings" window opens instead of turning the air con on/off. The settings window is where the user can turn off/on, set temp etc.

Can we get a config setting or a fix for this? As it, there is a high risk the unit will encounter damage from the constant on/off switching.

**Comment by nitaybz** [comment]
No, this is HomeKit behavior... not a plugin option

**Comment by SeanHama** [comment]
Thanks & understoor. @nitaybz
