### ISSUE TITLE
Fan speed slider - remove "off'

### ISSUE THREAD

**Issue by SeanHama** [nitaybz/homebridge-cool-automation#5]
Is there a way we can edit configure or completely remove the "OFF" (far left slider setting) for the Fan Speed, its redundant considering we can turn the fan off from the temperature gauge setting. @nitaybz

**Comment by SeanHama** [comment]
@nitaybz Hi Nitay, just checking into to see if this can be implemented pls?

**Comment by SeanHama** [comment]
Hello, any chance this can be done pls?

**Comment by nitaybz** [comment]
Hey, you have to notice that there are few different things here, there is fan speed that is inside the HeaterCooler accessory settings. and there is also the fan accessory that is only controlling the fan mode, setting the fan there is controlling the fan mode.

anyway, when setting the real fanspeed to 0 it actually turn off the AC, this is a normal behavior of HomeKit and there is no way for me to remove it
