### ISSUE TITLE
CoolMasterNet

### ISSUE THREAD

**Issue by riedelcastro** [nitaybz/homebridge-cool-automation#8]
Does this plugin also work for the CoolMasterNet:

http://www.coolmasternet.co.uk/

Thanks!

**Comment by netanelassor** [comment]
following....

**Comment by kapps7** [comment]
I thought it was for this, keen to know as well

**Comment by gordonxman** [comment]
Yes it works with my CoolMasterNet

**Comment by nitaybz** [comment]
yes it does
