### ISSUE TITLE
Problem Sending Command: ls2

### ISSUE THREAD

**Issue by mamsbens** [nitaybz/homebridge-cool-automation#9]
Hi 
I use a Synology nas via putty.I see all my unit configure in cool automation on the log but I have an error command is2 and at the end error 0. Could anyone tell me what I have to 
Rgds

**Comment by NawathaH** [comment]
having same problen and it says its not working because its cloud based

**Comment by osalzberg** [comment]
Any results?

**Comment by nitaybz** [comment]
Cloud based devices does not allow any other integrations... your device can't work with this plugin, sorry...
